version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: docs/source/requirements.txt

build:
  tools:
    python: "3.10"
  commands:
    - pip install .
    - sphinx-build -b html docs/source docs/build